update README.md and fix compile issues for bitcoin-core v22.0, v25.0 and v27.0

diff --git a/core/22.0/Dockerfile b/core/22.0/Dockerfile
--- a/core/22.0/Dockerfile
+++ b/core/22.0/Dockerfile
@@ -1,35 +1,55 @@
-FROM debian:bullseye-slim
+FROM debian:bookworm-slim
+
+ENV BITCOIN_VERSION 22.0
+
+# add multiple platform support
+ARG TARGETARCH
+RUN echo "Ok, I'm building $BITCOIN_VERSION for $TARGETARCH"
 
 RUN groupadd -r bitcoin && useradd -r -m -g bitcoin bitcoin
 
+# download dependencies
 RUN set -ex \
-	&& apt-get update \
-	&& apt-get install -qq --no-install-recommends ca-certificates dirmngr gosu gpg gpg-agent wget \
-	&& rm -rf /var/lib/apt/lists/*
+    && apt-get update \
+    && apt-get install -qq --no-install-recommends ca-certificates dirmngr gosu gpg gpg-agent wget \
+    && rm -rf /var/lib/apt/lists/*
 
-ENV BITCOIN_VERSION 22.0
-ENV BITCOIN_URL https://bitcoin.org/bin/bitcoin-core-22.0/bitcoin-22.0-x86_64-linux-gnu.tar.gz
-ENV BITCOIN_SHA256 59ebd25dd82a51638b7a6bb914586201e67db67b919b2a1ff08925a7936d1b16 
-ENV BITCOIN_ASC_URL https://bitcoin.org/bin/bitcoin-core-22.0/SHA256SUMS.asc
-ENV BITCOIN_PGP_KEY 74E2DEF5D77260B98BC19438099BAD163C70FBFA,9D3CC86A72F8494342EA5FD10A41BDC3F4FAFF1C,9D3CC86A72F8494342EA5FD10A41BDC3F4FAFF1C 
-
-# install bitcoin binaries
+# download and install bitcoin binaries
 RUN set -ex \
-	&& cd /tmp \
-	&& wget -qO bitcoin.tar.gz "$BITCOIN_URL" \
-	&& echo "$BITCOIN_SHA256 bitcoin.tar.gz" | sha256sum -c - \
-	&& gpg --keyserver keyserver.ubuntu.com --recv-keys "$BITCOIN_PGP_KEY" \
-	&& wget -qO bitcoin.asc "$BITCOIN_ASC_URL" \
-	&& gpg --verify bitcoin.asc \
-	&& tar -xzvf bitcoin.tar.gz -C /usr/local --strip-components=1 --exclude=*-qt \
-	&& rm -rf /tmp/*
+    && cd /tmp \
+    && case ${TARGETARCH} in \
+         arm64) \
+           echo "Target: $TARGETARCH"; \
+           export BITCOIN_URL="https://bitcoin.org/bin/bitcoin-core-22.0/bitcoin-22.0-aarch64-linux-gnu.tar.gz" ;\
+           export BITCOIN_SHA256="ac718fed08570a81b3587587872ad85a25173afa5f9fbbd0c03ba4d1714cfa3e" ;\
+           env ;\
+           ;; \
+         amd64) \
+           echo "Target: $TARGETARCH"; \
+           export BITCOIN_URL="https://bitcoin.org/bin/bitcoin-core-22.0/bitcoin-22.0-x86_64-linux-gnu.tar.gz" ;\
+           export BITCOIN_SHA256="59ebd25dd82a51638b7a6bb914586201e67db67b919b2a1ff08925a7936d1b16" ;\
+           ;; \
+         arm) \
+           echo "Target: $TARGETARCH"; \
+           export BITCOIN_URL="https://bitcoin.org/bin/bitcoin-core-22.0/bitcoin-22.0-arm-linux-gnueabihf.tar.gz" ;\
+           export BITCOIN_SHA256="b8713c6c5f03f5258b54e9f436e2ed6d85449aa24c2c9972f91963d413e86311" ;\
+           ;; \
+         *) \
+           echo "unable to build for target: $TARGETARCH" ;\
+           exit 1 ;\
+           ;; \
+       esac \
+    && wget -qO bitcoin.tar.gz "$BITCOIN_URL" \
+    && echo "$BITCOIN_SHA256 bitcoin.tar.gz" | sha256sum -c - \
+    && tar -xzvf bitcoin.tar.gz -C /usr/local --strip-components=1 --exclude=*-qt \
+    && rm -rf /tmp/*
 
 # create data directory
 ENV BITCOIN_DATA /data
 RUN mkdir "$BITCOIN_DATA" \
-	&& chown -R bitcoin:bitcoin "$BITCOIN_DATA" \
-	&& ln -sfn "$BITCOIN_DATA" /home/bitcoin/.bitcoin \
-	&& chown -h bitcoin:bitcoin /home/bitcoin/.bitcoin
+    && chown -R bitcoin:bitcoin "$BITCOIN_DATA" \
+    && ln -sfn "$BITCOIN_DATA" /home/bitcoin/.bitcoin \
+    && chown -h bitcoin:bitcoin /home/bitcoin/.bitcoin
 VOLUME /data
 
 COPY docker-entrypoint.sh /entrypoint.sh
diff --git a/core/25.0/Dockerfile b/core/25.0/Dockerfile
--- a/core/25.0/Dockerfile
+++ b/core/25.0/Dockerfile
@@ -1,35 +1,55 @@
-FROM debian:bullseye-slim
+FROM debian:bookworm-slim
+
+ENV BITCOIN_VERSION 25.0
+
+# add multiple platform support
+ARG TARGETARCH
+RUN echo "Ok, I'm building $BITCOIN_VERSION for $TARGETARCH"
 
 RUN groupadd -r bitcoin && useradd -r -m -g bitcoin bitcoin
 
+# download dependencies
 RUN set -ex \
-	&& apt-get update \
-	&& apt-get install -qq --no-install-recommends ca-certificates dirmngr gosu gpg gpg-agent wget \
-	&& rm -rf /var/lib/apt/lists/*
+    && apt-get update \
+    && apt-get install -qq --no-install-recommends ca-certificates dirmngr gosu gpg gpg-agent wget \
+    && rm -rf /var/lib/apt/lists/*
 
-ENV BITCOIN_VERSION 25.0
-ENV BITCOIN_URL https://bitcoin.org/bin/bitcoin-core-25.0/bitcoin-25.0-x86_64-linux-gnu.tar.gz
-ENV BITCOIN_SHA256 33930d432593e49d58a9bff4c30078823e9af5d98594d2935862788ce8a20aec 
-ENV BITCOIN_ASC_URL https://bitcoin.org/bin/bitcoin-core-25.0/SHA256SUMS.asc
-ENV BITCOIN_PGP_KEY 9D3CC86A72F8494342EA5FD10A41BDC3F4FAFF1C 
-
-# install bitcoin binaries
+# download and install bitcoin binaries
 RUN set -ex \
-	&& cd /tmp \
-	&& wget -qO bitcoin.tar.gz "$BITCOIN_URL" \
-	&& echo "$BITCOIN_SHA256 bitcoin.tar.gz" | sha256sum -c - \
-	&& gpg --keyserver keyserver.ubuntu.com --recv-keys "$BITCOIN_PGP_KEY" \
-	&& wget -qO bitcoin.asc "$BITCOIN_ASC_URL" \
-	&& gpg --verify bitcoin.asc \
-	&& tar -xzvf bitcoin.tar.gz -C /usr/local --strip-components=1 --exclude=*-qt \
-	&& rm -rf /tmp/*
+    && cd /tmp \
+    && case ${TARGETARCH} in \
+         arm64) \
+           echo "Target: $TARGETARCH"; \
+           export BITCOIN_URL="https://bitcoin.org/bin/bitcoin-core-25.0/bitcoin-25.0-aarch64-linux-gnu.tar.gz" ;\
+           export BITCOIN_SHA256="3a7bdd959a0b426624f63f394f25e5b7769a5a2f96f8126dcc2ea53f3fa5212b" ;\
+           env ;\
+           ;; \
+         amd64) \
+           echo "Target: $TARGETARCH"; \
+           export BITCOIN_URL="https://bitcoin.org/bin/bitcoin-core-25.0/bitcoin-25.0-x86_64-linux-gnu.tar.gz" ;\
+           export BITCOIN_SHA256="33930d432593e49d58a9bff4c30078823e9af5d98594d2935862788ce8a20aec" ;\
+           ;; \
+         arm) \
+           echo "Target: $TARGETARCH"; \
+           export BITCOIN_URL="https://bitcoin.org/bin/bitcoin-core-25.0/bitcoin-25.0-arm-linux-gnueabihf.tar.gz" ;\
+           export BITCOIN_SHA256="e537c8630b05e63242d979c3004f851fd73c2a10b5b4fdbb161788427c7b3c0f" ;\
+           ;; \
+         *) \
+           echo "unable to build for target: $TARGETARCH" ;\
+           exit 1 ;\
+           ;; \
+       esac \
+    && wget -qO bitcoin.tar.gz "$BITCOIN_URL" \
+    && echo "$BITCOIN_SHA256 bitcoin.tar.gz" | sha256sum -c - \
+    && tar -xzvf bitcoin.tar.gz -C /usr/local --strip-components=1 --exclude=*-qt \
+    && rm -rf /tmp/*
 
 # create data directory
 ENV BITCOIN_DATA /data
 RUN mkdir "$BITCOIN_DATA" \
-	&& chown -R bitcoin:bitcoin "$BITCOIN_DATA" \
-	&& ln -sfn "$BITCOIN_DATA" /home/bitcoin/.bitcoin \
-	&& chown -h bitcoin:bitcoin /home/bitcoin/.bitcoin
+    && chown -R bitcoin:bitcoin "$BITCOIN_DATA" \
+    && ln -sfn "$BITCOIN_DATA" /home/bitcoin/.bitcoin \
+    && chown -h bitcoin:bitcoin /home/bitcoin/.bitcoin
 VOLUME /data
 
 COPY docker-entrypoint.sh /entrypoint.sh
